### PR TITLE
Update deps, fix test coverage, linting

### PR DESCRIPTION
**Pull request by zemccartney**
- Updates slew of deps
- Fix missing test coverage
- General linting
- Update travis node versions

### CODE REVIEW

**Comment by zemccartney** [comment]
Note that this work doesn't include any sort of integration yet i.e. I didn't use this updated version in a project, confirming it still works as expected. Do we have a preferred way of running such a test?

**Comment by devinivy** [comment]
I think the primary way to do that is to build locally then npm link it into a project.

**Comment by devinivy** [comment]
You could also publish a beta then allow many folks to pull it into their project to test prior to a "latest" release (in npm tag speak).  This looks great, by the way—thanks!

**Comment by zemccartney** [comment]
🙏 thanks for checking this out!
and cool, dig both of those suggestions, I'll try to find time soon to try one/both out.

Probably should have asked this at the beginning, before doing this work 🤡  : What's the future of `strange-auth`?
I took a brief look at using the strangeluv user recipe as a base for an integration environment here, but of course realized it doesn't use `strange-auth`. Though it seems the gap between here and there is `strange-middle-end` compatibility; so more specifically, is the next step for `strange-auth` something like refactoring it to work more closely with `strange-middle-end` as a sort of plugin?

Clearly I'm way out of touch here; sorry for the flail. Thanks for all the help!

**Comment by devinivy** [comment]
Oh no way, I think you are v much _in touch_ 😏.  I think strange-auth will look pretty different in the future.  Half of strange-auth is allowing one to author an async action given just an async function: now that is all taken care of generically by strange-middle-end.  I think you're dead on that strange-auth will look like a plugin, which in our case is a mod-creator (i.e. a function returning a strange-middle-end mod).

**Comment by zemccartney** [comment]
🎩 🎩 🎩 
thanks, bub! that all makes sense. so cool to think of authoring various state mgmt features as mod-creators, I can _feel_ the time and boilerplate savings. mmm

**Comment by zemccartney** [comment]
Closing since effectively blocked till we sort out strange-auth's next direction

**Pull request closed without merging**
